[package]
name = "mozzart-core"
version = "0.1.0"
edition = "2021"
authors.workspace = true
description = "Core music theory functionality"
license.workspace = true
repository.workspace = true

[dependencies]
paste = "1.0" 